# Generated by Django 3.0.4 on 2021-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('time_blinking', models.FloatField()),
                ('too_sleepy', models.BooleanField()),
            ],
        ),
    ]
