# Generated by Django 3.0.4 on 2021-10-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211024_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='id',
            new_name='_id',
        ),
    ]
