# Generated by Django 3.0.4 on 2021-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211024_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='_id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
