# Generated by Django 3.0.4 on 2021-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211024_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDriver',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('time_blinking', models.TextField()),
                ('too_sleepy', models.TextField()),
                ('username', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'dashboard_driver',
                'managed': False,
            },
        ),
    ]
